version: '3.8'
services:
  db:
    build: .
    container_name: urinalysis_backend
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: urinalysis_backend_database
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_urine}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_urine}
    ports:
      - 3307:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
