name: githubactions-urinalysis

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest
    name: Run Test and Send Report
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Docker run
        run: docker compose up -d

      - name: Test with Gradle
        run: ./gradlew test
        if: always()
        with: ${{secret.MYSQL_PASSWORD_urine}}

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          job_name: 'Test Report'

      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'reviewdog'
          checkstyle_config: 'config/checkstyle/checkstyle.xml'
          workdir: 'src/main'
          level: error

      - name: Run SpotBugs
        run: ./gradlew spotbugsMain
        if: always()

      - name: Upload SpotBugs Report
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: spotbugs-result
          path: build/reports/spotbugs/main.html

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/reports/jacoco/test/jacocoTestReport.xml

      - name: Actions Status Discord
        uses: sarisia/actions-status-discord@v1.11.1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_URINALYSIS_WEBHOOK }}
